#!/bin/csh -f

if ($1 == "") then
  set DSP=XMLibA.dsp
endif
if ($1 == 0) then
  set DSP=XMLibA_none.dsp
endif
if ($1 == 1) then
  set DSP=XMLibA_all.dsp
endif


cat Start1.dsp >! $DSP
cat Release.define >> $DSP

find ../BA -name \*. -exec ../build/catdefine {} $1 \; >> $DSP
find ../Audio -name \*. -exec ../build/catdefine {} $1 \; >> $DSP
find ../Video -name \*. -exec ../build/catdefine {} $1 \; >> $DSP
find ../MDS -name \*. -exec ../build/catdefine {} $1 \; >> $DSP

cat Debug.define >>$DSP

find ../BA -name \*. -exec ../build/catdefine {} $1 \; >> $DSP
find ../Audio -name \*. -exec ../build/catdefine {} $1 \; >> $DSP
find ../Video -name \*. -exec ../build/catdefine {} $1 \; >> $DSP
find ../MDS -name \*. -exec ../build/catdefine {} $1 \; >> $DSP

cat Start2.dsp >> $DSP
cat BA1.dsp >>$DSP

find ../Audio -name \*. -exec ../build/catdsp {} $1 \; >> $DSP

cat Tail.dsp >>$DSP


